# Generated by Django 4.2.7 on 2025-04-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_present", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["session", "timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("session_date", models.DateField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "camera_mode",
                    models.CharField(
                        choices=[("WEBCAM", "Webcam"), ("ESP32", "ESP32-CAM")],
                        default="WEBCAM",
                        max_length=10,
                    ),
                ),
                ("esp32_ip", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-session_date", "name"],
            },
        ),
    ]
